### ISSUE TITLE
[FEATURE REQUEST] Store whether "Classic" game is soloduo/flex/draft/quickplay

### ISSUE THREAD

**Issue by ceselder** [FFFFFFFXXXXXXX/league_record#17] opened 2024-02-10 10:39 UTC
Right now, these are all marked as "Game mode: Classic". I can't imagine the LCU doesn't provide a way to differentiate between them, since the post screen lobby does show stuff like lp gains and it must be getting them from the /lol-end-of-game/ endpoint that you use, right?

LCU is documentation hell, so I'm not sure whether this is 100% the case though.

I'd try to implement it myself but sadly I've never written rust before

**Comment by FFFFFFFXXXXXXX** [comment] 2024-02-12 00:58
Yeah, the "gameMode" in the metadata is a bit of a misnomer.
It actually is just the type of map that's being played. So ARAM, Summoners Rift or Twisted Treeline (doesn't exist anymore).
And for some reason Practicetool is it's own type of "Map" because of riots spaghetti code.

I'll have to look a little more into how to best get this information because (like everything else LoL API related) it's a big mess.
I am pretty sure it's possible tho.

**Comment by FFFFFFFXXXXXXX** [comment] 2024-02-19 00:06
duplicate of #18

**Closed by FFFFFFFXXXXXXX** 2024-02-19 00:06 UTC
