### ISSUE TITLE
Replay doesnt show Kills/Death/etc and Show No data

### ISSUE THREAD

**Issue by QiyanuReeves** [FFFFFFFXXXXXXX/league_record#24] opened 2024-03-24 00:33 UTC
Hello so ive noticed that most of my replayed games i dont see where for example i get a kill and when I die, only the (raw) footage and instead of showing my final score and Victory or Defeat in shows No data.

I have a game where it works as it should and many games where it doesnt, its just i don't know which log to send you.

**Comment by judehek** [comment] 2024-03-24 22:09
having this issue as well- from looking at logs seems to be an issue with process_data not firing- not exactly sure why (maybe endofgame related) interestly it works perfectly in practice tool games

**Comment by FFFFFFFXXXXXXX** [comment] 2024-03-24 22:12
Are using version 1.19.2 released ~4 days ago?
It included a fix for a bug where sometimes the game data failed to be collected properly.

**Comment by QiyanuReeves** [comment] 2024-03-24 22:16
Ive been using another version, Ill load a game and see if it works properly.

**Comment by judehek** [comment] 2024-03-24 23:58
been using latest version, just tried again with latest version and still persists

**Comment by QiyanuReeves** [comment] 2024-03-25 00:42
I Played some games and the outcome was the same. Here are the most recent logs i found in the logs section.
[2024-03-25_00-19.log](https://github.com/FFFFFFFXXXXXXX/league_record/files/14737460/2024-03-25_00-19.log)
[2024-03-24_14-36.log](https://github.com/FFFFFFFXXXXXXX/league_record/files/14737461/2024-03-24_14-36.log)
[2024-03-23_14-52.log](https://github.com/FFFFFFFXXXXXXX/league_record/files/14737462/2024-03-23_14-52.log)

**Comment by FFFFFFFXXXXXXX** [comment] 2024-03-25 02:01
It seems there is a bug where if you alt + f4 to skip the nexus explode animation the game-data might fail to be collected.
Is that what is happening?
I'll have a fix for it in the next release.

And thx for the logs 👍🏽

**Comment by judehek** [comment] 2024-03-25 02:17
i don't think this is the issue, but i'll play another one to double check and post logs. that could be an issue as well though.

**Comment by FFFFFFFXXXXXXX** [comment] 2024-03-25 23:29
[Pre-release 1.19.3](https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/1.19.3) is out now. It includes a fix for the issue with alt + f4 described above and should also fix your issues. I also added some more logging in the section of the code that the problem is occurring in - so that should help aswell in case the problem is not fixed.

**Comment by ceselder** [comment] 2024-03-26 20:06
I never alt f4, but I do click the continue button before its there and that would get me to end screen faster than normal so idk

**Comment by FFFFFFFXXXXXXX** [comment] 2024-03-27 10:28
Does the issue still occur with the new pre-release?

**Comment by ceselder** [comment] 2024-03-27 13:40
Will test and report back

**Comment by QiyanuReeves** [comment] 2024-03-29 15:34
Hello again,I tested out the new version and everything works as it should. Even When I AL4 + F4. Thanks a lot.

**Comment by FFFFFFFXXXXXXX** [comment] 2024-03-29 19:50
Nice, thanks for your help.

Fixed in release [v1.19.3](https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.19.3)

**Closed by FFFFFFFXXXXXXX** 2024-03-29 19:50 UTC
