### ISSUE TITLE
Application randomly closing/crashing?

### ISSUE THREAD

**Issue by judehek** [FFFFFFFXXXXXXX/league_record#8] opened 2023-11-25 00:04 UTC
my friends and i love this application. it seems like as of yesterday its been randomly closing while recording, and we haven't been able to record any games since- possibly from new patch? tried running as admin, i also ran with -d, i included the output. 
[logs.txt](https://github.com/FFFFFFFXXXXXXX/league_record/files/13462598/logs.txt)

**Comment by FFFFFFFXXXXXXX** [comment] 2023-11-25 01:30
Hey, thx for the logs.
Sadly it doesn't seem like there is anything obviously wrong in the logs.
I don't think it's the new patch since it still works for me. 

So the problem is that the program closes as soon as a game starts? Every time or only sometimes?
Do all your friends have the exact same problem or are there differences?

In the meantime you could try re-installing (make sure the whole `C:\Program Files\LeagueRecord` folder is gone after uninstalling) or you could try the version of the program without the installer (the .zip on the release page).

It's always quite hard to diagnose bugs over the internet.

**Comment by judehek** [comment] 2023-11-25 05:42
huh, how strange. Yep, every game it crashes, it seems to crash as soon as loading screen ends? we all have the same problem. 

i assumed it was an issue with the app, but if it works for you maybe its something else we all have in common. tried reinstalling, even deleted settings file, also tried portable version- no luck. I saw you changed some stuff so I built the latest, here are new logs if it helps, ill keep trying stuff in the meantime:
[logs.txt](https://github.com/FFFFFFFXXXXXXX/league_record/files/13463093/logs.txt)

**Comment by FFFFFFFXXXXXXX** [comment] 2023-11-25 18:19
The game crashing as soon as the loading screen ends kind of makes sense. The recorder process gets started/initialized as soon as the loading screen starts which is the main part of the logs.
When the loading screen is over the actual recording starts and the application somehow crashes.

So it seems there is a problem when hooking the LoL process / starting the recording.

---

Could you try building the example code from https://github.com/FFFFFFFXXXXXXX/libobs-recorder?
`cargo build --example recorder` should build a `./target/debug/recorder.exe`

This is my minimum viable example I test the recorder part of the application with.
To run it move `recorder.exe` to the ./libobs/ folder in your installation.
Open a commandline in that folder and run it from there (it probably requires admin permissions if your installation folder is in `C:\Program Files`).

If everything runs fine there should be a bunch of logs and then `started recording: Ok(())` and after 10s the program stops, having written a `output.mp4` file to the same folder. The `.mp4` should be a recording of the currently running LoL ingame window or just a black screen if no game is running.

That could give us some more info.

---

Maybe you could check if there were any windows updates or program installations the day the app stopped working.
Since I use the same library as OBS to record stuff you could check the known application conflicts for OBS https://obsproject.com/kb/known-conflicts.

**Comment by judehek** [comment] 2023-11-25 20:11
I built the recorder and everything works fine- it records the game if its open etc.
logs: 
[recorder test.txt](https://github.com/FFFFFFFXXXXXXX/league_record/files/13465111/recorder.test.txt)


I don't have any of the known conflicts either

**Comment by FFFFFFFXXXXXXX** [comment] 2023-11-25 23:07
Now that is even weirder.
I'll try to look into it.

**Comment by FFFFFFFXXXXXXX** [comment] 2023-11-26 17:32
Ok, I added a bunch of extra logs that might show something.
In case you have time at some point could you build the newest version of the code. (don't forget to ´cargo update`) and post the logs again?

**Comment by judehek** [comment] 2023-11-26 21:42
did you get the latest one to run? whenever i run it just instantly closes- 

i updated cargo and everything, ran: cargo +nightly build -Z bindeps --release
then copied libobs + app into a separate folder

PS H:\vscode\test leaguerecord> ./app -d | echo
LeagueRecord v1.14.3
PS H:\vscode\test leaguerecord>

**Comment by FFFFFFFXXXXXXX** [comment] 2023-11-26 22:44
ah, super sry. It should work now

**Comment by judehek** [comment] 2023-11-26 23:37
[new logs.txt](https://github.com/FFFFFFFXXXXXXX/league_record/files/13468439/new.logs.txt)
doesn't look like anything helpful

**Comment by FFFFFFFXXXXXXX** [comment] 2023-11-26 23:47
Thanks, that helped me narrow it down a bit.
My current suspicion is there is something weird going on with the ingame API.

In what region are you playing? NA? I am testing on EUW. Maybe there is a small difference in some API response somewhere.

**Comment by judehek** [comment] 2023-11-27 00:25
yep, that could be it, we are all on NA

**Comment by FFFFFFFXXXXXXX** [comment] 2023-11-27 01:09
alright, with the newest commit we should see in the logs whats wrong with the received data

**Comment by judehek** [comment] 2023-11-27 01:58
[logs.txt](https://github.com/FFFFFFFXXXXXXX/league_record/files/13468969/logs.txt)
yep

**Comment by FFFFFFFXXXXXXX** [comment] 2023-11-28 00:26
I have pushed my workaround. I have tested it on my account and it still works for the old summoner names.
Would be awesome if you could test it with the your riot id before I publish a new release.
The program should definitely not crash anymore. It might not pick up the summoner name / champion data correctly though.

**Comment by judehek** [comment] 2023-11-28 00:41
yep it works! it doesn't collect any data, it just says "no data" but thats fine

**Comment by FFFFFFFXXXXXXX** [comment] 2023-11-28 01:27
could you post one more log of the now working version, thx

**Comment by judehek** [comment] 2023-11-28 06:33
[logs.txt](https://github.com/FFFFFFFXXXXXXX/league_record/files/13484360/logs.txt)

**Comment by FFFFFFFXXXXXXX** [comment] 2023-11-28 14:37
I have released the new version https://github.com/FFFFFFFXXXXXXX/league_record/releases/tag/v1.14.4 with the fix so i'll close this issue.

Thanks for all the help troubleshooting the problem!

**Closed** 2023-11-28 14:37 UTC
